{
 "title": "Stateless Block Verfier",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "netowrk",
    "query": "host.docker.internal:9091, host.docker.internal:9092"
   }
  ]
 },
 "panels": [
  {
   "title": "Block Per Seconds",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(block_counter_total{instance=\"$netowrk\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetched Block Height",
   "type": "stat",
   "description": "Current height of fetched block for verifying.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fetched_rpc_block_height{instance=\"$netowrk\"}",
     "legendFormat": "verified block height"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "stat",
   "description": "Latest block height of current rpc node.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_rpc_block_height{instance=\"$netowrk\"}",
     "legendFormat": "verified block height"
    }
   ]
  },
  {
   "title": "Distance To Head",
   "type": "stat",
   "description": "The distance from fetched block to latest. If this increases, we have trouble following the network.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latest_rpc_block_height{instance=\"$netowrk\"} - fetched_rpc_block_height{instance=\"$netowrk\"}",
     "legendFormat": "verified block height"
    }
   ]
  },
  {
   "title": "Estimate Time To Catch Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(latest_rpc_block_height{instance=\"$netowrk\"} - fetched_rpc_block_height{instance=\"$netowrk\"}) / rate(block_counter_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verification Error",
   "type": "stat",
   "description": "Verification  error occurs in the last minute.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(verification_error_total{instance=\"$netowrk\"}[1m])",
     "legendFormat": "verified block height"
    }
   ]
  },
  {
   "title": "Total Block Verification Duration",
   "type": "heatmap",
   "description": "Total time consumed to verify a block.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(le) (increase(total_block_verification_duration_bucket{instance=\"$netowrk\"}[$__interval]) / ignoring(le)  group_left increase(total_block_verification_duration_count{instance=\"$netowrk\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Block Verification Duration Distribution",
   "type": "bargauge",
   "description": "Distribution of the total time consumed to verify a block.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(total_block_verification_duration_bucket{instance=\"$netowrk\"}[$__range]) / ignoring(le) group_left increase(total_block_verification_duration_count{instance=\"$netowrk\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Build Zktrie DB Duration",
   "type": "heatmap",
   "description": "Time consumed to update zktrie state from one  block trace.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (increase(build_zktrie_db_duration_bucket{instance=\"$netowrk\"}[$__interval]) / ignoring(le)  group_left increase(build_zktrie_db_duration_count{instance=\"$netowrk\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handle Block Duration",
   "type": "heatmap",
   "description": "Time cost in revm handle_block, most related with EVM execution.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (increase(handle_block_duration_bucket{instance=\"$netowrk\"}[$__interval]) / ignoring(le)  group_left increase(handle_block_duration_count{instance=\"$netowrk\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transact Commit Duration",
   "type": "heatmap",
   "description": "Time consumed to transact_commit one tx.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (increase(transact_commit_duration_bucket{instance=\"$netowrk\"}[$__interval]) / ignoring(le)  group_left increase(transact_commit_duration_count{instance=\"$netowrk\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Changes Duration",
   "type": "heatmap",
   "description": "Time consumed to populate database changes to zktrie once.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (increase(commit_changes_duration_bucket{instance=\"$netowrk\"}[$__interval]) / ignoring(le)  group_left increase(commit_changes_duration_count{instance=\"$netowrk\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZkTrie Get Duration",
   "type": "heatmap",
   "description": "Time consumed to get a zktrie node.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(zktrie_get_duration_bucket{instance=\"$netowrk\"}[$__interval]) / ignoring(le)  group_left increase(zktrie_get_duration_count{instance=\"$netowrk\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZkTrie Update Duration",
   "type": "heatmap",
   "description": "Time consumed to update a zktrie node.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(zktrie_update_duration_bucket{instance=\"$netowrk\"}[$__interval]) / ignoring(le)  group_left increase(zktrie_update_duration_count{instance=\"$netowrk\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZkTrie Delete Duration",
   "type": "heatmap",
   "description": "Time consumed to delete a zktrie node.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(zktrie_delete_duration_bucket{instance=\"$netowrk\"}[$__interval]) / ignoring(le)  group_left increase(zktrie_delete_duration_count{instance=\"$netowrk\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZkTrie Commit Duration",
   "type": "heatmap",
   "description": "Time consumed to commit zktrie changes.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(zktrie_commit_duration_bucket{instance=\"$netowrk\"}[$__interval]) / ignoring(le)  group_left increase(zktrie_commit_duration_count{instance=\"$netowrk\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}