[package]
name = "sbv"
homepage = "https://github.com/scroll-tech/stateless-block-verifier/tree/master/crates/sbv"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sbv-chainspec.workspace = true
sbv-core.workspace = true
sbv-kv.workspace = true
sbv-primitives.workspace = true
sbv-trie.workspace = true
sbv-helpers.workspace = true

[features]
scroll = ["sbv-chainspec/scroll", "sbv-core/scroll", "sbv-primitives/scroll"]
debug-account = ["sbv-core/debug-account", "sbv-helpers/debug-account"]
debug-storage = ["sbv-core/debug-storage", "sbv-helpers/debug-storage"]
dev = ["sbv-core/dev", "sbv-helpers/dev", "sbv-primitives/dev", "sbv-trie/dev"]
metrics = ["sbv-core/metrics", "sbv-helpers/metrics"]

# sp1 related
sp1 = ["sbv-core/sp1", "sbv-primitives/sp1"]
cycle-tracker = ["sbv-core/cycle-tracker", "sbv-primitives/cycle-tracker"]
ordered-db = ["sbv-core/ordered-db"]