[package]
name = "sbv"
homepage = "https://github.com/scroll-tech/stateless-block-verifier/tree/master/crates/sbv"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
sbv-core.workspace = true
sbv-primitives.workspace = true
sbv-utils.workspace = true

[features]
debug-account = ["sbv-core/debug-account", "sbv-utils/debug-account"]
debug-storage = ["sbv-core/debug-storage", "sbv-utils/debug-storage"]
dev = ["sbv-core/dev", "sbv-utils/dev", "sbv-primitives/dev"]
metrics = ["sbv-core/metrics", "sbv-utils/metrics"]

# sp1 related
sp1 = ["sbv-core/sp1", "sbv-primitives/sp1"]
cycle-tracker = ["sbv-core/cycle-tracker", "sbv-primitives/cycle-tracker"]
ordered-db = ["sbv-core/ordered-db"]